### Get all products
GET http://127.0.0.1:3000/products

### Get product by ID
GET http://127.0.0.1:3000/products/<id>

### Get products by Brand
GET http://127.0.0.1:3000/products/<brand>

### Add a new product
POST http://127.0.0.1:3000/products
Content-Type: application/json

{
    "id":3,
    "name": "Pixel 8",
    "price": 699,
    "brand": "Google"
}

### Update a product
PUT http://127.0.0.1:3000/products/<id>
Content-Type: application/json

{
    "id":2,
    "name": "iPhone 15 Pro",
    "price": 1099,
    "brand": "Apple"
}

### Delete a product
DELETE http://127.0.0.1:3000/products/<id>